---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-and-run-image-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-1-23-6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-run-pipeline-run-{time}
spec:
  serviceAccountName: build-bot
  timeouts:
    pipeline: "4h4m0s"
    tasks: "4h0m0s"
  pipelineSpec:
    workspaces:
      - name: source-ws
      - name: output-ws
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source-ws
        params:
          - name: url
            value: https://github.com/ericgraf/openstack-image-generator.git
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
          - name: revision
            value: initial-dev

      - name: docker-build
        taskRef:
          name: docker-build
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source-ws
        params:
          - name: dockerfile
            value: ./build-image/Dockerfile
          - name: context
            value: ./build-image/
          - name: image
            value: {HOST_IP}:5000/admin/image-builder
          - name: insecure_registry
            value: {HOST_IP}:5000

      - name: build-capo-openstack-image
        timeout: 4h
        taskRef:
          name: build-capo-openstack-image
        runAfter:
            - docker-build
        params:
          - name: ACCELERATOR
            value: 'none'
          - name: KUBERNETES_SERIES
            value: '1.22'
          - name: KUBERNETES_VERSION
            value: '1.22.9'
          - name: PACKER_LOG
            value: '1'
          - name: build-image
            value: localhost:5000/admin/image-builder
        workspaces:
        - name: output
          workspace: output-ws

      - name: list-output-files
        taskRef:
          name: list-output-files
        runAfter:
            - build-capo-openstack-image
        workspaces:
        - name: output
          workspace: output-ws

  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: build-and-run-image-ws-pvc

    - name: output-ws  
      persistentVolumeClaim:
        claimName: output-1-23-6