apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: verify-no-file-exists-without-resource
spec:
  params:
    - name: "path"
  resources:
    - name: optional-workspace
      type: git
      optional: true
  check:
    image: alpine
    script: 'test ! -f $(resources.optional-workspace.path)/$(params.path)'