---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-docker-build-local
spec:
  selector:
    matchLabels:
      app: registry-docker-build-local
  template:
    metadata:
      labels:
        app: registry-docker-build-local
    spec:
      containers:
      - name: registry-docker-build-local
        image: registry:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          hostPort: 5000   
        volumeMounts:  
          - name: registry-vol
            mountPath: /var/lib/registry
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: registry-vol
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app: registry-docker-build-local
  ports:
  - port: 5000
    targetPort: 5000