apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gen-checksum
spec:
  workspaces:
  - name: output
  params:
  - name: filename
    default: filename
  steps:
    - name: gen-checksum
      image: ubuntu:latest
      env:
        - name: FILENAME
          value: $(params.filename)

      script: |
                sha256sum $(workspaces.output.path)/output/${FILENAME}/${FILENAME}
                sha256sum $(workspaces.output.path)/output/${FILENAME}/${FILENAME} > $(workspaces.output.path)/output/${FILENAME}/${FILENAME}.sha256sums