apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli-upload
spec:
  params:
    - name: SCRIPT
      default: |
        aws s3 ls s3:/<bkup>/
        #aws s3 cp $(workspaces.source.path)/test s3://<bk>/test/
  steps:
    - name: aws-cli-upload
      taskRef:
        name: aws-cli
      workspaces:
      - name: secrets
      - name: source
  workspaces:
    - name: secrets
      secret:
        secretName: aws-credentials
    - name: source